create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  email text not null,
  phone text not null,
  postal_code text not null,
  prefecture text not null,
  address text not null,
  building text,
  note text,
  items jsonb not null,
  total integer not null,
  status text not null default 'received',
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;
